package com.langzonedev.rippertipper.data

import com.langzonedev.rippertipper.model.Tip

// Generated by backend/update_predictions.py. Do not edit by hand.
object PredictionSnapshot {
    const val roundName = "Round 16"
    const val roundDates = "25–28 June 2026 · Adelaide time"
    const val status = "26 models + match context"
    const val updatedLabel = "Updated 21 June, 6:12 pm"

    val tips = listOf(
        Tip(
            id = 38622,
            awayTeam = "Sydney",
            homeTeam = "Brisbane Lions",
            recommendedTeam = "Brisbane Lions",
            confidencePercent = 52,
            startTime = "Thu 7:00 pm",
            venue = "Gabba",
            reason = "16 of 25 tracked models favour Brisbane Lions. Sydney rates better historically, keeping this pick tighter. Recent form runs against the pick, so confidence is restrained.",
            modelCount = 25,
        ),
        Tip(
            id = 38625,
            awayTeam = "Greater Western Sydney",
            homeTeam = "Hawthorn",
            recommendedTeam = "Hawthorn",
            confidencePercent = 74,
            startTime = "Fri 7:10 pm",
            venue = "MCG",
            reason = "25 of 26 tracked models favour Hawthorn. Hawthorn also rates higher on results-based team strength. The forecast looks settled, so weather should have little influence.",
            modelCount = 26,
        ),
        Tip(
            id = 38623,
            awayTeam = "West Coast",
            homeTeam = "Carlton",
            recommendedTeam = "Carlton",
            confidencePercent = 83,
            startTime = "Sat 12:45 pm",
            venue = "Marvel Stadium",
            reason = "25 of 25 tracked models favour Carlton. Carlton also rates higher on results-based team strength. Carlton has the stronger recent five-game record.",
            modelCount = 25,
        ),
        Tip(
            id = 38624,
            awayTeam = "Richmond",
            homeTeam = "Collingwood",
            recommendedTeam = "Collingwood",
            confidencePercent = 87,
            startTime = "Sat 3:45 pm",
            venue = "MCG",
            reason = "25 of 25 tracked models favour Collingwood. Collingwood also rates higher on results-based team strength. The forecast looks settled, so weather should have little influence.",
            modelCount = 25,
        ),
        Tip(
            id = 38627,
            awayTeam = "Adelaide",
            homeTeam = "Port Adelaide",
            recommendedTeam = "Adelaide",
            confidencePercent = 72,
            startTime = "Sat 7:05 pm",
            venue = "Adelaide Oval",
            reason = "24 of 25 tracked models favour Adelaide. Adelaide also rates higher on results-based team strength. Adelaide has the stronger recent five-game record.",
            modelCount = 25,
        ),
        Tip(
            id = 38626,
            awayTeam = "Essendon",
            homeTeam = "North Melbourne",
            recommendedTeam = "North Melbourne",
            confidencePercent = 68,
            startTime = "Sun 2:45 pm",
            venue = "Marvel Stadium",
            reason = "25 of 25 tracked models favour North Melbourne. North Melbourne also rates higher on results-based team strength. North Melbourne has the stronger recent five-game record.",
            modelCount = 25,
        ),
        Tip(
            id = 38628,
            awayTeam = "Gold Coast",
            homeTeam = "Fremantle",
            recommendedTeam = "Fremantle",
            confidencePercent = 79,
            startTime = "Sun 4:40 pm",
            venue = "Optus Stadium",
            reason = "24 of 25 tracked models favour Fremantle. Fremantle also rates higher on results-based team strength. Fremantle has the stronger recent five-game record.",
            modelCount = 25,
        ),
    )
}
