package com.langzonedev.rippertipper.data

import com.langzonedev.rippertipper.model.Tip

// Generated by backend/update_predictions.py. Do not edit by hand.
object PredictionSnapshot {
    const val roundName = "Round 20"
    const val roundDates = "25–26 July 2026 · Adelaide time"
    const val status = "31 models + injury/form context"
    const val updatedLabel = "Updated 24 July, 11:39 pm"

    val tips = listOf(
        Tip(
            id = 38657,
            awayTeam = "Gold Coast",
            homeTeam = "Carlton",
            recommendedTeam = "Carlton",
            confidencePercent = 54,
            startTime = "Sat 12:35 pm",
            venue = "Marvel Stadium",
            reason = "29 of 31 tracked models favour Carlton. Carlton has the stronger recent five-game record. Carlton's recent scoring margins are materially stronger.",
            modelCount = 31,
            kickoffEpochMillis = 1784948700000L,
            baselineModelHomeProbability = 0.590045,
            contextHomeProbability = 0.360314,
        ),
        Tip(
            id = 38659,
            awayTeam = "Essendon",
            homeTeam = "Hawthorn",
            recommendedTeam = "Hawthorn",
            confidencePercent = 94,
            startTime = "Sat 3:45 pm",
            venue = "MCG",
            reason = "31 of 31 tracked models favour Hawthorn. Hawthorn also rates higher on results-based team strength. Hawthorn has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784960100000L,
            baselineModelHomeProbability = 0.926371,
            contextHomeProbability = 0.973659,
        ),
        Tip(
            id = 38658,
            awayTeam = "Sydney",
            homeTeam = "Greater Western Sydney",
            recommendedTeam = "Sydney",
            confidencePercent = 65,
            startTime = "Sat 4:05 pm",
            venue = "ENGIE Stadium",
            reason = "29 of 31 tracked models favour Sydney. Sydney also rates higher on results-based team strength. Sydney has the cleaner current availability profile.",
            modelCount = 31,
            kickoffEpochMillis = 1784961300000L,
            baselineModelHomeProbability = 0.4177,
            contextHomeProbability = 0.104386,
        ),
        Tip(
            id = 38662,
            awayTeam = "Richmond",
            homeTeam = "Western Bulldogs",
            recommendedTeam = "Western Bulldogs",
            confidencePercent = 91,
            startTime = "Sat 7:10 pm",
            venue = "Marvel Stadium",
            reason = "31 of 31 tracked models favour Western Bulldogs. Western Bulldogs also rates higher on results-based team strength. Western Bulldogs has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784972400000L,
            baselineModelHomeProbability = 0.868126,
            contextHomeProbability = 1.046643,
        ),
        Tip(
            id = 38656,
            awayTeam = "Port Adelaide",
            homeTeam = "Brisbane Lions",
            recommendedTeam = "Brisbane Lions",
            confidencePercent = 90,
            startTime = "Sun 12:40 pm",
            venue = "Gabba",
            reason = "31 of 31 tracked models favour Brisbane Lions. Brisbane Lions also rates higher on results-based team strength. Brisbane Lions has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1785035400000L,
            baselineModelHomeProbability = 0.840758,
            contextHomeProbability = 1.104798,
        ),
        Tip(
            id = 38660,
            awayTeam = "St Kilda",
            homeTeam = "North Melbourne",
            recommendedTeam = "St Kilda",
            confidencePercent = 75,
            startTime = "Sun 2:45 pm",
            venue = "Marvel Stadium",
            reason = "31 of 31 tracked models favour St Kilda. St Kilda also rates higher on results-based team strength. Squiggle power rankings also lean toward St Kilda.",
            modelCount = 31,
            kickoffEpochMillis = 1785042900000L,
            baselineModelHomeProbability = 0.345761,
            contextHomeProbability = -0.084305,
        ),
    )
}
