package com.langzonedev.rippertipper.data

import com.langzonedev.rippertipper.model.Tip

// Generated by backend/update_predictions.py. Do not edit by hand.
object PredictionSnapshot {
    const val roundName = "Round 19"
    const val roundDates = "18–19 July 2026 · Adelaide time"
    const val status = "31 models + injury/form context"
    const val updatedLabel = "Updated 18 July, 5:36 pm"

    val tips = listOf(
        Tip(
            id = 38647,
            awayTeam = "Carlton",
            homeTeam = "Collingwood",
            recommendedTeam = "Collingwood",
            confidencePercent = 61,
            startTime = "Sat 7:05 pm",
            venue = "MCG",
            reason = "30 of 31 tracked models favour Collingwood. Collingwood also rates higher on results-based team strength. Squiggle power rankings also lean toward Collingwood.",
            modelCount = 31,
            kickoffEpochMillis = 1784367300000L,
            baselineModelHomeProbability = 0.593974,
            contextHomeProbability = 0.681996,
        ),
        Tip(
            id = 38655,
            awayTeam = "Brisbane Lions",
            homeTeam = "West Coast",
            recommendedTeam = "Brisbane Lions",
            confidencePercent = 95,
            startTime = "Sat 7:40 pm",
            venue = "Optus Stadium",
            reason = "31 of 31 tracked models favour Brisbane Lions. Brisbane Lions also rates higher on results-based team strength. Brisbane Lions has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784369400000L,
            baselineModelHomeProbability = 0.160381,
            contextHomeProbability = -0.34135,
        ),
        Tip(
            id = 38652,
            awayTeam = "Hawthorn",
            homeTeam = "Richmond",
            recommendedTeam = "Hawthorn",
            confidencePercent = 95,
            startTime = "Sun 12:40 pm",
            venue = "MCG",
            reason = "31 of 31 tracked models favour Hawthorn. Hawthorn also rates higher on results-based team strength. Hawthorn has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784430600000L,
            baselineModelHomeProbability = 0.096074,
            contextHomeProbability = -0.113354,
        ),
        Tip(
            id = 38650,
            awayTeam = "Western Bulldogs",
            homeTeam = "Gold Coast",
            recommendedTeam = "Western Bulldogs",
            confidencePercent = 57,
            startTime = "Sun 2:45 pm",
            venue = "People First Stadium",
            reason = "8 of 31 tracked models favour Western Bulldogs. Western Bulldogs also rates higher on results-based team strength. Western Bulldogs has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784438100000L,
            baselineModelHomeProbability = 0.543365,
            contextHomeProbability = 0.047925,
        ),
        Tip(
            id = 38648,
            awayTeam = "Greater Western Sydney",
            homeTeam = "Essendon",
            recommendedTeam = "Greater Western Sydney",
            confidencePercent = 92,
            startTime = "Sun 4:10 pm",
            venue = "Marvel Stadium",
            reason = "31 of 31 tracked models favour Greater Western Sydney. Greater Western Sydney also rates higher on results-based team strength. Greater Western Sydney has the stronger recent five-game record.",
            modelCount = 31,
            kickoffEpochMillis = 1784443200000L,
            baselineModelHomeProbability = 0.190503,
            contextHomeProbability = -0.31458,
        ),
    )
}
